player-command = player-verb-phrase | player-verb-noun-phrase ;
admin-command = admin-verb-string-phrase | player-verb-phrase | player-verb-noun-phrase ;
player-verb-noun-phrase = { article | preposition } ( look-verb ) { article | preposition } noun { article | preposition };
player-verb-phrase = player-verb ;
admin-verb-string-phrase = admin-verb string ;
player-verb = look-verb | brief-verb | north-verb | south-verb | east-verb
            | west-verb | northeast-verb | northwest-verb | southeast-verb
            | southwest-verb | up-verb | down-verb ;
admin-verb = error-verb ;
look-verb = "l" | "look" ;
brief-verb = "brief" ;
north-verb = "n" | "north" ;
south-verb = "s" | "south" ;
east-verb = "e" | "east" ;
west-verb = "w" | "west" ;
northeast-verb = "ne" | "northeast" ;
northwest-verb = "nw" | "northwest" ;
southeast-verb = "se" | "southeast" ;
southwest-verb = "sw" | "southwest" ;
up-verb = "u" | "up" ;
down-verb = "d" | "down" ;
error-verb = "error" ;
preposition = "aboard" | "about" | "above" | "absent" | "across" | "after"
            | "against" | "along" | "alongside" | "amid" | "apropos" | "apud"
            | "around" | "as" | "astride" | "at" | "atop" | "ontop" | "bar"
            | "before" | "behind" | "beneath" | "beside" | "besides"
            | "between" | "beyond" | "but" | "by" | "chez" | "circa" | "come"
            | "despite" | "down" | "during" | "except" | "for" | "from" | "in"
            | "inside" | "into" | "less" | "like" | "minus" | "near"
            | "notwithstanding" | "of" | "off" | "on" | "onto" | "opposite"
            | "out" | "outside" | "over" | "pace" | "past" | "per" | "post"
            | "pre" | "pro" | "qua" | "re" | "sans" | "save" | "short"
            | "since" | "than" | "thorugh" | "throughout" | "to" | "toward"
            | "under" | "underneath" | "unlike" | "until" | "up" | "upon"
            | "upside" | "versus" | "via" | "vice" | "with" | "within"
            | "without" | "worth ;
article = "the" " | " "a" " | " "an" ;
noun = string ;
string = { character } ;
character = letter | digit | symbol | space;
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
symbol = "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*"
       | "(" | ")" | "-" | "_" | "=" | "+" | "[" | "]"
       | "{" | "}" | "\" | "|" | ";" | ":" | "'" | '"'
       | "," | "<" | "." | ">" | "/" | "?" | "`" | "~" ;
space = " " ;
